version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  version: 2
  test:
    jobs:
      - test_dotnetcore
      - test_dotnetframework

jobs:
  test_dotnetcore:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1-focal
      - image: amazon/dynamodb-local
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.ServerSdk.DynamoDB -f netstandard2.0
      - run: dotnet test test/LaunchDarkly.ServerSdk.DynamoDB.Tests -f netcoreapp2.1

  test_dotnetframework:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: download DynamoDB
          command: |
            New-Item "dynamodb-local" -ItemType "directory" | Out-Null
            $ProgressPreference = "SilentlyContinue"
            wget "https://s3.us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip" -OutFile "./dynamodb-local/dynamodb.zip"
            Expand-Archive -Path ./dynamodb-local/dynamodb.zip -DestinationPath ./dynamodb-local
      - run:
          name: run DynamoDB
          command: java -D"java.library.path=./dynamodb-local/DynamoDBLocal_lib" -jar ./dynamodb-local/DynamoDBLocal.jar -sharedDb
          background: true
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.ServerSdk.DynamoDB -f net452
      - run: dotnet test test/LaunchDarkly.ServerSdk.DynamoDB.Tests -f net452
