version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.0
jobs:
  test-2.0:
    docker:
      - image: microsoft/dotnet:2.0-sdk-jessie
      - image: amazon/dynamodb-local
    steps:
      - run:
          name: install packages
          command: apt-get -q update && apt-get install -qy awscli
      - checkout
      - run: aws s3 cp s3://launchdarkly-pastebin/ci/dotnet/LaunchDarkly.DynamoDB.snk LaunchDarkly.DynamoDB.snk
      - run: dotnet restore
      - run: dotnet build LaunchDarkly.Client.DynamoDB -f netstandard2.0
      - run: dotnet test LaunchDarkly.Client.DynamoDB.Tests/LaunchDarkly.Client.DynamoDB.Tests.csproj -f netcoreapp2.0
