version: 2

publications:
  - url: https://nuget.org/packages/LaunchDarkly.ServerSdk.DynamoDB
    description: NuGet

jobs:
  - docker: {}
    template:
      name: dotnet-linux
      skip:
        - test
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0

documentation:
  title: LaunchDarkly Server-Side .NET SDK DynamoDB Integration
  gitHubPages: true
