publications:
  - url: https://nuget.org/packages/LaunchDarkly.ServerSdk.DynamoDB
    description: NuGet

circleci:
  windows:
    context: org-global
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: net452

template:
  name: dotnet-windows
  skip:
    - test

documentation:
  title: LaunchDarkly Server-Side .NET SDK DynamoDB Integration
  githubPages: true
