publications:
  - url: https://nuget.org/packages/LaunchDarkly.ServerSdk.DynamoDB
    description: NuGet

circleci:
  windows:
    context: org-global
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: net45

template:
  name: dotnet-windows
  skip:
    - test  # tests require DynamoDB - run them only in CI

documentation:
  title: LaunchDarkly SDK DynamoDB Integration
  githubPages: true
