version: 2

publications:
  - url: https://nuget.org/packages/LaunchDarkly.ServerSdk.DynamoDB
    description: NuGet

jobs:
  - docker: {}
    template:
      name: dotnet6-linux
      skip:
        - test
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0

branches:
  - name: main
    description: 3.x - for SDK 7+
  - name: 2.x
    description: 2.x - for SDK 6.x
  - name: 1.x
    description: for SDK 5.x

documentation:
  title: LaunchDarkly Server-Side .NET SDK DynamoDB Integration
  gitHubPages: true
